apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
data:
  postgres-user: dGVzdA==
  postgres-password: dGVzdA==
  postgres-db: dGVzdA==
  jwt-secret: YzU1MzQ3YmI2MzNjZThkMGY0ODI0YjAxN2Y3MGRkYjBlMDMzNmI3ODlhNWRiZjc0NDliNTRhZjE1NWVhZjk3Mw==
  jwt-refresh-secret: YzA4ZjdmZDZiNjcxNTJhZmFjMTI5Y2Q1MTYyOTVlYzUyNTc2NjAzYTBkMjUzYzRiMmE0NDdkZDg5NzJmNTUx

