apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagement-deployment
  labels:
    app: usermanagement
spec:
  replicas: 3
  selector:
    matchLabels:
      app: usermanagement
  template:
    metadata:
      labels:
        app: usermanagement
    spec:
      containers:
      - name: usermanagement
        image: ghcr.io/maalsi23-bloc-3/usermanagementms:1ed9e05f95ba44e7e05b3d9e55811eaf20074831
        ports:
        - containerPort: 3000
        env:
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-host
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: POSTGRES_PASSWORDç
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-db
        - name: ENABLE_CORS
          value: "true"
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_PORT
          value: "5432"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: jwt-secret
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: jwt-refresh-secret
        - name: ACCESS_TOKEN_EXPIRATION
          value: "1d"
        - name: REFRESH_TOKEN_EXPIRATION
          value: "1y"
---
apiVersion: v1
kind: Service
metadata:
  name: usermanagement-service
spec:
  selector:
    app: usermanagement
  ports:
  -protocol: TCP
    port: 80
    targetPort: 3000