apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagement-deployment
  labels:
    app: usermanagement
spec:
  replicas: 3
  selector:
    matchLabels:
      app: usermanagement
  template:
    metadata:
      labels:
        app: usermanagement
    spec:
      containers:
      - name: usermanagement
        image: ghcr.io/maalsi23-bloc-3/usermanagementms:1ed9e05f95ba44e7e05b3d9e55811eaf20074831
        ports:
        - containerPort: 3000
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres-url
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres-port
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-secret
              key: postgres-db
        - name: ENABLE_CORS
          valueFrom:
            configMapKeyRef: 
              name: usermanagement-config
              key: enable-cors
        - name: PORT
          valueFrom:
            configMapKeyRef: 
              name: usermanagement-config
              key: port
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: usermanagement-config
              key: node-env
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: usermanagement-secret
              key: jwt-secret
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: usermanagement-secret
              key: jwt-refresh-secret
        - name: ACCESS_TOKEN_EXPIRATION
          valueFrom:
            configMapKeyRef:
              name: usermanagement-config
              key: access-token-expiration
        - name: REFRESH_TOKEN_EXPIRATION
          valueFrom:
            configMapKeyRef:
              name: usermanagement-config
              key: refresh-token-expiration
---
apiVersion: v1
kind: Service
metadata:
  name: usermanagement-service
spec:
  type: NodePort
  selector:
    app: usermanagement
  ports:
  -protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30000