apiVersion: v1
kind: Secret
metadata:
  name: usermanagement-secret
  namespace: default
type: Opaque
data:
  jwt-secret: YzU1MzQ3YmI2MzNjZThkMGY0ODI0YjAxN2Y3MGRkYjBlMDMzNmI3ODlhNWRiZjc0NDliNTRhZjE1NWVhZjk3Mw==
  jwt-refresh-secret: YzA4ZjdmZDZiNjcxNTJhZmFjMTI5Y2Q1MTYyOTVlYzUyNTc2NjAzYTBkMjUzYzRiMmE0NDdkZDg5NzJmNTUx

