apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: cert-issuer
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
  - host: cube3.caravelabs.tech
    http:
      paths:
        - path: /user(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: usermanagement-service
              port:
                number: 80
        - path: /products(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: products-service
              port:
                number: 80
  - host: argocd.caravelabs.tech
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: argocd-server
              port:
                name: https
  tls:
  - hosts: 
    - cube3.caravelabs.tech
    secretName: cube3-tls
  - hosts:
    - argocd.example.com
    secretName: argocd-server-tls # as expected by argocd-server