apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cube3-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/MAALSI23-BLOC-3/infra.git'
    targetRevision: HEAD
    path: 'productsMS'
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true