apiVersion: v1
kind: Secret
metadata:
  name: usermanagement-secret
  # namespace: production
type: Opaque
data:
  jwt-secret: secret
  jwt-refresh-secret: secret
  postgres-user: secret
  postgres-password: secret
  postgres-db: secret
